### ISSUE TITLE
Not working in latest hassio and homeassistant

### ISSUE THREAD

**Issue by ptbsare** [cyberjunky/home-assistant-arpscan_tracker#10]
It seems that hassio removed the arp-scan command.
arp-scan
zsh: command not found

**Comment by ptbsare** [comment]
hassio 6.6 kernel 5.10.75
ha core: 2021.11.2

**Comment by cyberjunky** [comment]
Hi @ptbsare strange, arp-scan is still in the Dockerfile here

https://github.com/home-assistant/docker/blob/master/Dockerfile

And it still works in my setup:
```
2021-11-25 10:15:48 DEBUG (SyncWorker_8) [custom_components.arpscan_tracker.device_tracker] Scanning...
2021-11-25 10:15:50 DEBUG (SyncWorker_8) [custom_components.arpscan_tracker.device_tracker] Scandata Interface: eth0, type: EN10MB, MAC: 00:1e:06:42:79:18, IPv4: 192.168.2.215
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.2.100 f0:c7:7f:8e:c5:19 Texas Instruments
...
```
Can you enable debug and check what is goin on?

```
logger:
  default: warn
  logs:
    custom_components.arpscan_tracker: debug
```

![image](https://user-images.githubusercontent.com/5447161/143414910-2b7cc2c2-41ad-4600-8e1d-45c841f450db.png)
![image](https://user-images.githubusercontent.com/5447161/143414970-c4798719-8c03-46ad-aa85-b1f2d27b5709.png)

**Comment by ptbsare** [comment]
Updating my config, upgrading HA and then restarting HA resolves the issue. Maybe it is related to my wrong configuration. Thanks.

**Comment by cyberjunky** [comment]
Possibly, thanks for the reply!
