### ISSUE TITLE
friendly names

### ISSUE THREAD

**Issue by DzgHomeCastle** [cyberjunky/home-assistant-arpscan_tracker#15]
Is there a possibility to configure friendly_name for devices?
Eg. Device is discovered as device_tracker.dasdl32oi2hdslcsy,   but I would like to see  device_tracker.MyPhone.

**Comment by rbak69** [comment]
Hi @DzgHomeCastle  yes that is possible. Just go to the "known_devices.yaml" file and change the name of the discovered entry to whatever you like (and restart Home Assistant).

`# Network (WiFi)
# Mobile phones
myphone:
  name: My Mobile Phone
  mac: aa:bb:cc:dd:ee:ff
  icon: mdi:cellphone
  track: true` 
  
  This results in your device to be known within Home Assistant as "device_tracker.myphone"
