### ISSUE TITLE
How delete?

### ISSUE THREAD

**Issue by semikor** [cyberjunky/home-assistant-arpscan_tracker#16]
How do I remove the home-assistant-arpscan_tracker integration from Home Assistant?
And how do I delete all the objects created by integration???
They (objects) are not editable in the UI shell (((
Thanks!

**Comment by cyberjunky** [comment]
Delete integration via HACS, and the objects are stored in file known_devices.yaml, in the config directory, you can edit it with a editor addon, like vscode, or simpler one. You have to restart after editing the file.
