### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by AdmiralRaccoon** [cyberjunky/home-assistant-arpscan_tracker#7]
Hello,
this sounds like a stupid question, but how do I debug if arpscan is working at all? I read how people posted some debug log output herm but I can´t find anything in the HA Logs, except a warning that the arpscan_tracker integration hasn´t been tested. 
Though there aren´t any device_tracker.mac_adress entities available

Thank you,
Philipp

**Comment by cyberjunky** [comment]
@AdmiralRaccoon Hi.

I have updated the readme file.
Add below -or last part of it- to your config and restart home assistant.

```yaml
logger:
  default: info
  logs:
    custom_components.arpscan_tracker: debug
```

It can be two things, you are not running Home Assistant OS, but some other OS, and didn't install the arp-scan command.
Or you have to specify another/the correct network interface. Try to find out the name and specify it with the options.

**Comment by AdmiralRaccoon** [comment]
Ah, thank you, now it´s working. It was the wrong interface I selected.
