### ISSUE TITLE
Question about known_devices.yaml

### ISSUE THREAD

**Issue by AdmiralRaccoon** [cyberjunky/home-assistant-arpscan_tracker#8]
Hello again,
one question for my understanding. A user in a different thread here asked where to find the entities, and you replied with the known_devices.yaml.

Until know, I used the Fritz Device Tracker, which populated my known_devices.yaml and then I edited it for my purposed like name, icon, and so on.
If I know disable the Fritz Device Tracker, and only use the arpscan_tracker, will the devices being used that are already in the known_devices.yaml, or should I begin from scratch?

Thank you,
Philipp

**Comment by cyberjunky** [comment]
@AdmiralRaccoon It depends, not all device trackers store the reference in the same format.

These entries are generated by arp-scan:
```
728b46fe221e:
  name: 728b46fe221e
  mac: 72:8B:46:FE:22:1E
  icon:
  picture:
  track: true
```
So if Fritz also uses the mac address in lowercase all together before the first ":" you can simply disable fritz and enable arp-scan.
It then will use same entries and names/icon (I did change them myself too)

**Comment by AdmiralRaccoon** [comment]
works great so far, thank you for your work!
