### ISSUE TITLE
Android / Apple home and not_home issue

### ISSUE THREAD

**Issue by AdmiralRaccoon** [cyberjunky/home-assistant-arpscan_tracker#9]
Hello...
So one thing I found out after testing it a couple of minutes is that both my Apple and Android devices are playing home and not_home every minute.
Is this a known limitation due to the nature of energy savings in mobile devices, or are my values to short?

![image](https://user-images.githubusercontent.com/41727850/108906199-e6e91c80-7620-11eb-81d9-ca9f944c7e87.png)

My config:

`  - platform: arpscan_tracker
    interval_seconds: 15
    consider_home: 30
    track_new_devices: yes
    scan_options: " --interface=enp11s0 192.168.1.0/24 -g"`

**Comment by cyberjunky** [comment]
@AdmiralRaccoon Yes iPhones are difficult (I use this https://github.com/mudape/iphonedetect for them)
Some Androids (Samsung) have same issue, but my Pixel is fine. I'm not sure if specifying a higher consider_home parameter will work with arp_scan.
